const cards = [
    { name: 'arthur', img: 'Arthur.jpg', status: 'down' },
    { name: 'arthur', img: 'Arthur.jpg', status: 'down' },
    { name: 'batkid', img: 'batkid.jpg', status: 'down' },
    { name: 'batkid', img: 'batkid.jpg', status: 'down' },
    { name: 'captain armenia', img: 'captain-armenia.jpg', status: 'down' },
    { name: 'captain armenia', img: 'captain-armenia.jpg', status: 'down' },
    { name: 'captain-avenger', img: 'captain-avenger.jpg', status: 'down' },
    { name: 'captain-avenger', img: 'captain-avenger.jpg', status: 'down' },
    { name: 'deadpool', img: 'deadpool.jpg', status: 'down' },
    { name: 'deadpool', img: 'deadpool.jpg', status: 'up' },
    { name: 'shazam', img: 'shazam.jpg', status: 'down' },
    { name: 'shazam', img: 'shazam.jpg', status: 'down' },
    { name: 'super', img: 'super.jpg', status: 'down' },
    { name: 'super', img: 'super.jpg', status: 'down' },
    { name: 'tick', img: 'the-tick.jpg', status: 'down' },
    { name: 'tick', img: 'the-tick.jpg', status: 'down' },
    { name: 'bananaman', img: 'bananaman.jpg', status: 'up' },
    { name: 'bananaman', img: 'bananaman.jpg', status: 'down' },
    { name: 'cooperman', img: 'cooperman.jpg', status: 'down' },
    { name: 'cooperman', img: 'cooperman.jpg', status: 'down' },
    { name: 'blunderwoman', img: 'blunderwoman.jpg', status: 'down' },
    { name: 'blunderwoman', img: 'blunderwoman.jpg', status: 'down' },
    { name: 'kryptonite', img: 'kryptonite.jpg', status: 'up' },
    { name: 'kryptonite', img: 'kryptonite.jpg', status: 'down' },
    { name: 'kryptonite', img: 'kryptonite.jpg', status: 'down'}
];