const cards = [
    { name: 'arthur', img: "arthurImg", status: 'down' },
    { name: 'arthur', img: "arthurImg", status: 'down' },
    { name: 'batkid', img: "batkidImg", status: 'down' },
    { name: 'batkid', img: "batkidImg", status: 'down' },
    { name: 'captain armenia', img: "captainArmeniaImg", status: 'down' },
    { name: 'captain armenia', img: "captainArmeniaImg", status: 'down' },
    { name: 'captain-avenger', img: "captainAvengerImg", status: 'down' },
    { name: 'captain-avenger', img: "captainAvengerImg", status: 'down' },
    { name: 'superian', img: "superianImg", status: 'down' },
    { name: 'superian', img:  "superianImg", status: 'down' },
    { name: 'shazam', img: "shazam", status: 'down' },
    { name: 'shazam', img: "shazam", status: 'down' },
    { name: 'super', img: "superImg", status: 'down' },
    { name: 'super', img: "superImg", status: 'down' },
    { name: 'tick', img: "tickImg", status: 'down' },
    { name: 'tick', img: "tickImg", status: 'down' },
    { name: 'bananaman', img: "bananamanImg", status: 'down' },
    { name: 'bananaman', img: "bananamanImg", status: 'down' },
    { name: 'cooperman', img: "coopermanImg", status: 'down' },
    { name: 'cooperman', img: "coopermanImg", status: 'down' },
    { name: 'blunderwoman', img: "blunderwomanImg", status: 'down' },
    { name: 'blunderwoman', img: "blunderwomanImg", status: 'down' },
    { name: 'kryptonite', img: "kryptoniteImg", status: 'down' },
    { name: 'kryptonite', img: "kryptoniteImg", status: 'down' },
    { name: 'kryptonite', img: "kryptoniteImg", status: 'down'}
];
